<?php

return [
    'properties' => [
        'SupportedCurrencies' => [
            'GBP' => (object) [
                'code'                => 'GBP',
                'symbol'              => '&pound;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'British Pound Sterling',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'USD' => (object) [
                'code'                => 'USD',
                'symbol'              => '$',
                'symbol_position'     => 'BEFORE',
                'label'               => 'United States Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'EUR' => (object) [
                'code'                => 'EUR',
                'symbol'              => '&euro;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Euro',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'AFN' => (object) [
                'code'                => 'AFN',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Afghan Afghani',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'ALL' => (object) [
                'code'                => 'ALL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Albanian Lek',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'DZD' => (object) [
                'code'                => 'DZD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Algerian Dinar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'AOA' => (object) [
                'code'                => 'AOA',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Angolan Kwanza',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'ARS' => (object) [
                'code'                => 'ARS',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Argentine Peso',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'AMD' => (object) [
                'code'                => 'AMD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Armenian Dram',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'AWG' => (object) [
                'code'                => 'AWG',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Aruban Florin',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'AUD' => (object) [
                'code'                => 'AUD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Australian Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'AZN' => (object) [
                'code'                => 'AZN',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Azerbaijani Manat',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BSD' => (object) [
                'code'                => 'BSD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Bahamian Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BHD' => (object) [
                'code'                => 'BHD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Bahraini Dinar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BDT' => (object) [
                'code'                => 'BDT',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Bangladeshi Taka',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BBD' => (object) [
                'code'                => 'BBD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Barbadian Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BYR' => (object) [
                'code'                => 'BYR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Belarusian Ruble',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BZD' => (object) [
                'code'                => 'BZD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Belize Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BMD' => (object) [
                'code'                => 'BMD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Bermudan Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BTN' => (object) [
                'code'                => 'BTN',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Bhutanese Ngultrum',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BTC' => (object) [
                'code'                => 'BTC',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Bitcoin',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BOB' => (object) [
                'code'                => 'BOB',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Bolivian Boliviano',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BAM' => (object) [
                'code'                => 'BAM',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Bosnia-Herzegovina Convertible Mark',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BWP' => (object) [
                'code'                => 'BWP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Botswanan Pula',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BRL' => (object) [
                'code'                => 'BRL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Brazilian Real',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BND' => (object) [
                'code'                => 'BND',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Brunei Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BGN' => (object) [
                'code'                => 'BGN',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Bulgarian Lev',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MMK' => (object) [
                'code'                => 'MMK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Burmese Kyat',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'BIF' => (object) [
                'code'                => 'BIF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Burundian Franc',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'XOF' => (object) [
                'code'                => 'XOF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'CFA Franc BCEAO',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'XAF' => (object) [
                'code'                => 'XAF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'CFA Franc BEAC',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'XPF' => (object) [
                'code'                => 'XPF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'CFP Franc',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'KHR' => (object) [
                'code'                => 'KHR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Cambodian Riel',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'CAD' => (object) [
                'code'                => 'CAD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Canadian Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'CVE' => (object) [
                'code'                => 'CVE',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Cape Verdean Escudo',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'KYD' => (object) [
                'code'                => 'KYD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Cayman Islands Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'CLP' => (object) [
                'code'                => 'CLP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Chilean Peso',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'CLF' => (object) [
                'code'                => 'CLF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Chilean Unit of Account (UF)',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'CNY' => (object) [
                'code'                => 'CNY',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Chinese Yuan',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'COP' => (object) [
                'code'                => 'COP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Colombian Peso',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'KMF' => (object) [
                'code'                => 'KMF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Comorian Franc',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'CDF' => (object) [
                'code'                => 'CDF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Congolese Franc',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'CRC' => (object) [
                'code'                => 'CRC',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Costa Rican Colón',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'HRK' => (object) [
                'code'                => 'HRK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Croatian Kuna',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'CUP' => (object) [
                'code'                => 'CUP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Cuban Peso',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'CZK' => (object) [
                'code'                => 'CZK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Czech Republic Koruna',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'DKK' => (object) [
                'code'                => 'DKK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Danish Krone',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'DJF' => (object) [
                'code'                => 'DJF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Djiboutian Franc',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'DOP' => (object) [
                'code'                => 'DOP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Dominican Peso',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'XCD' => (object) [
                'code'                => 'XCD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'East Caribbean Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'EGP' => (object) [
                'code'                => 'EGP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Egyptian Pound',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'EEK' => (object) [
                'code'                => 'EEK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Estonian Kroon',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'ETB' => (object) [
                'code'                => 'ETB',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Ethiopian Birr',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'FKP' => (object) [
                'code'                => 'FKP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Falkland Islands Pound',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'FJD' => (object) [
                'code'                => 'FJD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Fijian Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'GMD' => (object) [
                'code'                => 'GMD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Gambian Dalasi',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'GEL' => (object) [
                'code'                => 'GEL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Georgian Lari',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'GHS' => (object) [
                'code'                => 'GHS',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Ghanaian Cedi',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'GIP' => (object) [
                'code'                => 'GIP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Gibraltar Pound',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'XAU' => (object) [
                'code'                => 'XAU',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Gold (troy ounce)',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'GTQ' => (object) [
                'code'                => 'GTQ',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Guatemalan Quetzal',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'GNF' => (object) [
                'code'                => 'GNF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Guinean Franc',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'GYD' => (object) [
                'code'                => 'GYD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Guyanaese Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'HTG' => (object) [
                'code'                => 'HTG',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Haitian Gourde',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'HNL' => (object) [
                'code'                => 'HNL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Honduran Lempira',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'HKD' => (object) [
                'code'                => 'HKD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Hong Kong Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'HUF' => (object) [
                'code'                => 'HUF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Hungarian Forint',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'ISK' => (object) [
                'code'                => 'ISK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Icelandic Króna',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'INR' => (object) [
                'code'                => 'INR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Indian Rupee',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'IDR' => (object) [
                'code'                => 'IDR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Indonesian Rupiah',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'IRR' => (object) [
                'code'                => 'IRR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Iranian Rial',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'IQD' => (object) [
                'code'                => 'IQD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Iraqi Dinar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'ILS' => (object) [
                'code'                => 'ILS',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Israeli New Sheqel',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'JMD' => (object) [
                'code'                => 'JMD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Jamaican Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'JPY' => (object) [
                'code'                => 'JPY',
                'symbol'              => '&yen;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Japanese Yen',
                'decimal_precision'   => 0,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'JEP' => (object) [
                'code'                => 'JEP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Jersey Pound',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'JOD' => (object) [
                'code'                => 'JOD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Jordanian Dinar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'KZT' => (object) [
                'code'                => 'KZT',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Kazakhstani Tenge',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'KES' => (object) [
                'code'                => 'KES',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Kenyan Shilling',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'KWD' => (object) [
                'code'                => 'KWD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Kuwaiti Dinar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'KGS' => (object) [
                'code'                => 'KGS',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Kyrgystani Som',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'LAK' => (object) [
                'code'                => 'LAK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Laotian Kip',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'LVL' => (object) [
                'code'                => 'LVL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Latvian Lats',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'LBP' => (object) [
                'code'                => 'LBP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Lebanese Pound',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'LSL' => (object) [
                'code'                => 'LSL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Lesotho Loti',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'LRD' => (object) [
                'code'                => 'LRD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Liberian Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'LYD' => (object) [
                'code'                => 'LYD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Libyan Dinar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'LTL' => (object) [
                'code'                => 'LTL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Lithuanian Litas',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MOP' => (object) [
                'code'                => 'MOP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Macanese Pataca',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MKD' => (object) [
                'code'                => 'MKD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Macedonian Denar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MGA' => (object) [
                'code'                => 'MGA',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Malagasy Ariary',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MWK' => (object) [
                'code'                => 'MWK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Malawian Kwacha',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MYR' => (object) [
                'code'                => 'MYR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Malaysian Ringgit',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MVR' => (object) [
                'code'                => 'MVR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Maldivian Rufiyaa',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MTL' => (object) [
                'code'                => 'MTL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Maltese Lira',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MRO' => (object) [
                'code'                => 'MRO',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Mauritanian Ouguiya',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MUR' => (object) [
                'code'                => 'MUR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Mauritian Rupee',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MXN' => (object) [
                'code'                => 'MXN',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Mexican Peso',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MDL' => (object) [
                'code'                => 'MDL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Moldovan Leu',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MNT' => (object) [
                'code'                => 'MNT',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Mongolian Tugrik',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MAD' => (object) [
                'code'                => 'MAD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Moroccan Dirham',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'MZN' => (object) [
                'code'                => 'MZN',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Mozambican Metical',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'NAD' => (object) [
                'code'                => 'NAD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Namibian Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'NPR' => (object) [
                'code'                => 'NPR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Nepalese Rupee',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'ANG' => (object) [
                'code'                => 'ANG',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Netherlands Antillean Guilder',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'TWD' => (object) [
                'code'                => 'TWD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'New Taiwan Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'NZD' => (object) [
                'code'                => 'NZD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'New Zealand Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'NIO' => (object) [
                'code'                => 'NIO',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Nicaraguan Córdoba',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'NGN' => (object) [
                'code'                => 'NGN',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Nigerian Naira',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'KPW' => (object) [
                'code'                => 'KPW',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'North Korean Won',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'NOK' => (object) [
                'code'                => 'NOK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Norwegian Krone',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'OMR' => (object) [
                'code'                => 'OMR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Omani Rial',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'PKR' => (object) [
                'code'                => 'PKR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Pakistani Rupee',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'PAB' => (object) [
                'code'                => 'PAB',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Panamanian Balboa',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'PGK' => (object) [
                'code'                => 'PGK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Papua New Guinean Kina',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'PYG' => (object) [
                'code'                => 'PYG',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Paraguayan Guarani',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'PEN' => (object) [
                'code'                => 'PEN',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Peruvian Nuevo Sol',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'PHP' => (object) [
                'code'                => 'PHP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Philippine Peso',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'PLN' => (object) [
                'code'                => 'PLN',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Polish Zloty',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'QAR' => (object) [
                'code'                => 'QAR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Qatari Rial',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'RON' => (object) [
                'code'                => 'RON',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Romanian Leu',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'RUB' => (object) [
                'code'                => 'RUB',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Russian Ruble',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'RWF' => (object) [
                'code'                => 'RWF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Rwandan Franc',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SHP' => (object) [
                'code'                => 'SHP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Saint Helena Pound',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SVC' => (object) [
                'code'                => 'SVC',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Salvadoran Colón',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'WST' => (object) [
                'code'                => 'WST',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Samoan Tala',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SAR' => (object) [
                'code'                => 'SAR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Saudi Riyal',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'RSD' => (object) [
                'code'                => 'RSD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Serbian Dinar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SCR' => (object) [
                'code'                => 'SCR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Seychellois Rupee',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SLL' => (object) [
                'code'                => 'SLL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Sierra Leonean Leone',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'XAG' => (object) [
                'code'                => 'XAG',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Silver (troy ounce)',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SGD' => (object) [
                'code'                => 'SGD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Singapore Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SBD' => (object) [
                'code'                => 'SBD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Solomon Islands Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SOS' => (object) [
                'code'                => 'SOS',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Somali Shilling',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'ZAR' => (object) [
                'code'                => 'ZAR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'South African Rand',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'KRW' => (object) [
                'code'                => 'KRW',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'South Korean Won',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'XDR' => (object) [
                'code'                => 'XDR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Special Drawing Rights',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'LKR' => (object) [
                'code'                => 'LKR',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Sri Lankan Rupee',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SDG' => (object) [
                'code'                => 'SDG',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Sudanese Pound',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SRD' => (object) [
                'code'                => 'SRD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Surinamese Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SZL' => (object) [
                'code'                => 'SZL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Swazi Lilangeni',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SEK' => (object) [
                'code'                => 'SEK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Swedish Krona',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'CHF' => (object) [
                'code'                => 'CHF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Swiss Franc',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'SYP' => (object) [
                'code'                => 'SYP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Syrian Pound',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'STD' => (object) [
                'code'                => 'STD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'São Tomé and Príncipe Dobra',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'TJS' => (object) [
                'code'                => 'TJS',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Tajikistani Somoni',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'TZS' => (object) [
                'code'                => 'TZS',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Tanzanian Shilling',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'THB' => (object) [
                'code'                => 'THB',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Thai Baht',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'TOP' => (object) [
                'code'                => 'TOP',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Tongan Paʻanga',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'TTD' => (object) [
                'code'                => 'TTD',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Trinidad and Tobago Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'TND' => (object) [
                'code'                => 'TND',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Tunisian Dinar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'TRY' => (object) [
                'code'                => 'TRY',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Turkish Lira',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'TMT' => (object) [
                'code'                => 'TMT',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Turkmenistani Manat',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'UGX' => (object) [
                'code'                => 'UGX',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Ugandan Shilling',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'UAH' => (object) [
                'code'                => 'UAH',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Ukrainian Hryvnia',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'AED' => (object) [
                'code'                => 'AED',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'United Arab Emirates Dirham',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'UYU' => (object) [
                'code'                => 'UYU',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Uruguayan Peso',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'UZS' => (object) [
                'code'                => 'UZS',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Uzbekistan Som',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'VUV' => (object) [
                'code'                => 'VUV',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Vanuatu Vatu',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'VEF' => (object) [
                'code'                => 'VEF',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Venezuelan Bolívar Fuerte',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'VND' => (object) [
                'code'                => 'VND',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Vietnamese Dong',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'YER' => (object) [
                'code'                => 'YER',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Yemeni Rial',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'ZMW' => (object) [
                'code'                => 'ZMW',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Zambian Kwacha',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'ZMK' => (object) [
                'code'                => 'ZMK',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Zambian Kwacha (pre-2013)',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
            'ZWL' => (object) [
                'code'                => 'ZWL',
                'symbol'              => '&curren;',
                'symbol_position'     => 'BEFORE',
                'label'               => 'Zimbabwean Dollar',
                'decimal_precision'   => 2,
                'decimal_symbol'      => '.',
                'thousands_separator' => ',',
            ],
        ],
    ],
    'services'   => [
        'Currency' => function () {
            if (class_exists('\App\Currency\Service\Currency')) {
                return new \App\Currency\Service\Currency();
            } else {
                return new \Nails\Currency\Service\Currency();
            }
        },
    ],
];
